name: PR Checks - Typecheck & Integration Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  typecheck-and-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prepare test configuration
        run: cp src/config.example.ts src/config.ts

      - name: Typecheck
        run: npm run typecheck

      - name: Integration tests
        run: node --expose-gc ./node_modules/.bin/jest tests/integration
